-- ═══════════════════════════════════════════════════════════════════════════
-- BHELVIZ — Oracle 19c Schema (Production)
-- Dual-layer encryption: Oracle TDE (at-rest) + AES-256-GCM (app-level)
-- All sensitive VARCHAR2 columns store AES-256-GCM ciphertext.
-- Decryption is client-side only — server never holds plaintext.
-- ═══════════════════════════════════════════════════════════════════════════


-- ── TABLESPACE (TDE-encrypted) ────────────────────────────────────────────
-- Execute as DBA before schema creation:
--
-- ADMINISTER KEY MANAGEMENT SET KEYSTORE OPEN
--   IDENTIFIED BY EXTERNAL STORE;
--
-- CREATE TABLESPACE bhelviz_data
--   DATAFILE '/oradata/bhelviz/bhelviz_data01.dbf' SIZE 500M AUTOEXTEND ON
--   ENCRYPTION USING AES256
--   DEFAULT STORAGE (ENCRYPT);
--
-- All tables should be created in this tablespace.


-- ── DEPARTMENT ────────────────────────────────────────────────────────────
CREATE TABLE department (
    department_id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dept_code             VARCHAR2(30)  NOT NULL,
    dept_name_enc         VARCHAR2(512) NOT NULL,  -- AES-256-GCM ciphertext
    parent_department_id  NUMBER        NULL,
    created_at            TIMESTAMP(6)  DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_dept_code    UNIQUE (dept_code),
    CONSTRAINT fk_dept_parent  FOREIGN KEY (parent_department_id)
                                REFERENCES department(department_id)
) TABLESPACE bhelviz_data;


-- ── ROLE LOOKUP ───────────────────────────────────────────────────────────
CREATE TABLE role_lu (
    role_code  VARCHAR2(30) PRIMARY KEY,
    role_name  VARCHAR2(100) NOT NULL,
    CONSTRAINT uq_role_name UNIQUE (role_name),
    CONSTRAINT ck_role_code CHECK (role_code IN ('EXECUTIVE','SUPERVISOR','WORKMAN'))
);


-- ── EMPLOYEE ──────────────────────────────────────────────────────────────
CREATE TABLE employee (
    employee_id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_no_enc      VARCHAR2(512)  NOT NULL,  -- AES-256-GCM ciphertext (deterministic for uniqueness)
    full_name_enc        VARCHAR2(1024) NOT NULL,  -- AES-256-GCM ciphertext
    department_id        NUMBER         NOT NULL,
    current_role_code    VARCHAR2(30)   NOT NULL,
    employment_status_enc VARCHAR2(512) NOT NULL,  -- AES-256-GCM ciphertext
    hired_at_enc         VARCHAR2(256)  NOT NULL,  -- AES-256-GCM ciphertext (date serialised to ISO string)
    active_flag          CHAR(1)        DEFAULT 'Y' NOT NULL,
    CONSTRAINT uq_employee_no  UNIQUE (employee_no_enc),  -- deterministic enc preserves uniqueness
    CONSTRAINT fk_emp_dept     FOREIGN KEY (department_id)   REFERENCES department(department_id),
    CONSTRAINT fk_emp_role     FOREIGN KEY (current_role_code) REFERENCES role_lu(role_code),
    CONSTRAINT ck_emp_active   CHECK (active_flag IN ('Y','N'))
) TABLESPACE bhelviz_data;


-- ── EMPLOYEE RELATION TYPE ────────────────────────────────────────────────
CREATE TABLE employee_relation_type_lu (
    relation_type_code  VARCHAR2(30)  PRIMARY KEY,
    relation_name       VARCHAR2(100) NOT NULL,
    CONSTRAINT uq_rel_name UNIQUE (relation_name)
);

INSERT INTO employee_relation_type_lu VALUES ('REPORTS_TO',  'Reports To');
INSERT INTO employee_relation_type_lu VALUES ('MENTORS',     'Mentors');
INSERT INTO employee_relation_type_lu VALUES ('PEER',        'Peer');
COMMIT;


-- ── EMPLOYEE RELATION ─────────────────────────────────────────────────────
CREATE TABLE employee_relation (
    relation_id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subject_employee_id  NUMBER       NOT NULL,
    object_employee_id   NUMBER       NOT NULL,
    relation_type_code   VARCHAR2(30) NOT NULL,
    valid_from           DATE         NOT NULL,
    valid_to             DATE         NULL,
    is_primary           CHAR(1)      DEFAULT 'N' NOT NULL,
    CONSTRAINT fk_rel_subject  FOREIGN KEY (subject_employee_id) REFERENCES employee(employee_id),
    CONSTRAINT fk_rel_object   FOREIGN KEY (object_employee_id)  REFERENCES employee(employee_id),
    CONSTRAINT fk_rel_type     FOREIGN KEY (relation_type_code)  REFERENCES employee_relation_type_lu(relation_type_code),
    CONSTRAINT ck_rel_not_self CHECK (subject_employee_id <> object_employee_id),
    CONSTRAINT ck_rel_primary  CHECK (is_primary IN ('Y','N'))
) TABLESPACE bhelviz_data;


-- ── EMPLOYEE ROLE HISTORY ─────────────────────────────────────────────────
CREATE TABLE employee_role_history (
    history_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id    NUMBER       NOT NULL,
    role_code      VARCHAR2(30) NOT NULL,
    effective_from DATE         NOT NULL,
    effective_to   DATE         NULL,
    CONSTRAINT fk_erh_emp  FOREIGN KEY (employee_id) REFERENCES employee(employee_id),
    CONSTRAINT fk_erh_role FOREIGN KEY (role_code)   REFERENCES role_lu(role_code)
) TABLESPACE bhelviz_data;


-- ── SHIFT ─────────────────────────────────────────────────────────────────
CREATE TABLE shift (
    shift_id    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shift_code  VARCHAR2(30)  NOT NULL,
    shift_name  VARCHAR2(100) NOT NULL,
    start_time  TIMESTAMP(6)  NOT NULL,
    end_time    TIMESTAMP(6)  NOT NULL,
    CONSTRAINT uq_shift_code UNIQUE (shift_code)
);

INSERT INTO shift (shift_code, shift_name, start_time, end_time)
VALUES ('MORNING',   'Morning Shift',   TO_TIMESTAMP('06:00','HH24:MI'), TO_TIMESTAMP('14:00','HH24:MI'));
INSERT INTO shift (shift_code, shift_name, start_time, end_time)
VALUES ('AFTERNOON', 'Afternoon Shift', TO_TIMESTAMP('14:00','HH24:MI'), TO_TIMESTAMP('22:00','HH24:MI'));
INSERT INTO shift (shift_code, shift_name, start_time, end_time)
VALUES ('NIGHT',     'Night Shift',     TO_TIMESTAMP('22:00','HH24:MI'), TO_TIMESTAMP('06:00','HH24:MI'));
COMMIT;


-- ── ATTENDANCE STATUS LOOKUP ──────────────────────────────────────────────
CREATE TABLE status_lu (
    status_code  VARCHAR2(30)  PRIMARY KEY,
    status_name             VARCHAR2(100) NOT NULL,
    CONSTRAINT uq_att_status UNIQUE (status_name)
);

INSERT INTO status_lu VALUES ('PRESENT',       'Present');
INSERT INTO status_lu VALUES ('ABSENT',        'Absent');
INSERT INTO status_lu VALUES ('LATE',          'Late');
INSERT INTO status_lu VALUES ('FALSE_PRESENT', 'False Present');
COMMIT;


-- ── ATTENDANCE (partitioned by month) ────────────────────────────────────
CREATE TABLE attendance (
    attendance_id          NUMBER GENERATED BY DEFAULT AS IDENTITY,
    employee_id            NUMBER       NOT NULL,
    shift_id               NUMBER       NOT NULL,
    att_date          TIMESTAMP(6) NOT NULL,                        -- clear (range queries)
    status_code VARCHAR2(30) NOT NULL,
    attendance_penalty     NUMBER(10,0) NULL,
    source_channel         VARCHAR2(30) NULL,
    device_id              VARCHAR2(64) NULL,
    created_at             TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_attendance          PRIMARY KEY (attendance_id, att_date),
    CONSTRAINT fk_att_employee        FOREIGN KEY (employee_id)            REFERENCES employee(employee_id),
    CONSTRAINT fk_att_shift           FOREIGN KEY (shift_id)               REFERENCES shift(shift_id),
    CONSTRAINT fk_att_status          FOREIGN KEY (status_code) REFERENCES status_lu(status_code),
    CONSTRAINT uq_att_business        UNIQUE (employee_id, shift_id, att_date),
    CONSTRAINT ck_att_penalty         CHECK (attendance_penalty IS NULL OR attendance_penalty < 0)
)
PARTITION BY RANGE (att_date)
INTERVAL (NUMTOYMINTERVAL(1, 'MONTH'))
(
    PARTITION p_2026_01 VALUES LESS THAN (TIMESTAMP '2026-02-01 00:00:00'),
    PARTITION p_2026_02 VALUES LESS THAN (TIMESTAMP '2026-03-01 00:00:00'),
    PARTITION p_2026_03 VALUES LESS THAN (TIMESTAMP '2026-04-01 00:00:00'),
    PARTITION p_2026_04 VALUES LESS THAN (TIMESTAMP '2026-05-01 00:00:00'),
    PARTITION p_2026_05 VALUES LESS THAN (TIMESTAMP '2026-06-01 00:00:00')
) TABLESPACE bhelviz_data;


-- ── TRIGGER: FALSE ATTENDANCE PENALTY ────────────────────────────────────
CREATE OR REPLACE TRIGGER trg_attendance_penalty
BEFORE INSERT OR UPDATE ON attendance
FOR EACH ROW
BEGIN
    IF :NEW.status_code = 'FALSE_PRESENT' THEN
        IF :NEW.attendance_penalty IS NULL THEN
            :NEW.attendance_penalty := -1;
        END IF;
        IF :NEW.attendance_penalty >= 0 THEN
            RAISE_APPLICATION_ERROR(-20001, 'False attendance penalty must be negative.');
        END IF;
    ELSE
        :NEW.attendance_penalty := NULL;
    END IF;
END;
/


-- ── INDEXES (B-tree for high cardinality, bitmap for low-cardinality reads) ─
-- B-tree
CREATE INDEX idx_emp_dept         ON employee(department_id);
CREATE INDEX idx_emp_role         ON employee(current_role_code);
CREATE INDEX idx_emp_no_enc       ON employee(employee_no_enc);   -- deterministic enc
CREATE INDEX idx_att_emp_shift_ts ON attendance(employee_id, shift_id, att_date);
CREATE INDEX idx_att_ts           ON attendance(att_date);
CREATE INDEX idx_att_shift_ts     ON attendance(shift_id, att_date);
CREATE INDEX idx_rel_subject      ON employee_relation(subject_employee_id, relation_type_code, valid_to);

-- Bitmap (read-heavy, low-DML tables only)
CREATE BITMAP INDEX bidx_att_status ON attendance(status_code);
CREATE BITMAP INDEX bidx_emp_active ON employee(active_flag);


-- ── VIEW: EMPLOYEE ATTENDANCE (ciphertext — no decryption) ───────────────
CREATE OR REPLACE VIEW employee_attendance_v AS
SELECT
    a.attendance_id,
    e.employee_no_enc,           -- ciphertext
    e.full_name_enc,             -- ciphertext
    d.dept_code,                 -- clear enum
    d.dept_name_enc,             -- ciphertext
    r.role_code,                 -- clear enum
    r.role_name,
    s.shift_code,                -- clear enum
    s.shift_name,
    a.att_date,             -- clear timestamp (needed for range queries)
    a.status_code,
    ast.status_name,
    a.attendance_penalty
FROM attendance a
JOIN employee              e   ON e.employee_id            = a.employee_id
JOIN department            d   ON d.department_id          = e.department_id
JOIN role_lu               r   ON r.role_code              = e.current_role_code
JOIN shift                 s   ON s.shift_id               = a.shift_id
JOIN status_lu  ast ON ast.status_code = a.status_code;


-- ── VIEW: EMPLOYEE DEPT ROLE ──────────────────────────────────────────────
CREATE OR REPLACE VIEW employee_dept_role_v AS
SELECT
    e.employee_id,
    e.employee_no_enc,
    e.full_name_enc,
    e.current_role_code,
    r.role_name,
    d.dept_code,
    d.dept_name_enc,
    e.hired_at_enc,
    e.active_flag
FROM employee e
JOIN department d ON d.department_id  = e.department_id
JOIN role_lu    r ON r.role_code      = e.current_role_code;


-- ── READ-ONLY APPLICATION ROLE ────────────────────────────────────────────
-- Per-user read-only role (created on approval — not shared):
--
-- CREATE ROLE bviz_ro_<user_id>;
-- GRANT CREATE SESSION TO bviz_ro_<user_id>;
-- GRANT SELECT ON bhelviz.employee_attendance_v  TO bviz_ro_<user_id>;
-- GRANT SELECT ON bhelviz.employee_dept_role_v   TO bviz_ro_<user_id>;
-- -- Explicitly revoke any write privileges:
-- REVOKE INSERT, UPDATE, DELETE, ALTER, DROP ON bhelviz.employee FROM bviz_ro_<user_id>;


-- ── ORACLE DATA REDACTION (for any remaining clear-text analytic columns) ─
-- BEGIN
--   DBMS_REDACT.ADD_POLICY(
--     object_schema => 'BHELVIZ',
--     object_name   => 'EMPLOYEE',
--     column_name   => 'ACTIVE_FLAG',
--     policy_name   => 'redact_active_flag',
--     function_type => DBMS_REDACT.PARTIAL,
--     expression    => '1=1'
--   );
-- END;
-- /


-- ── AUDIT TABLE ───────────────────────────────────────────────────────────
CREATE TABLE bhelviz_audit (
    audit_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_ts      TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    action        VARCHAR2(100) NOT NULL,
    actor         VARCHAR2(200) NOT NULL,
    detail        VARCHAR2(2000),
    level         VARCHAR2(10)  DEFAULT 'INFO' NOT NULL,
    session_id    VARCHAR2(64),
    ip_hash       VARCHAR2(32),
    CONSTRAINT ck_audit_level CHECK (level IN ('INFO','WARN','ERROR'))
) TABLESPACE bhelviz_data;

-- Audit table is INSERT-only for app users:
-- GRANT INSERT ON bhelviz_audit TO bviz_ro_<user_id>;
-- (No SELECT/UPDATE/DELETE — only SIEM service reads audit)
